# Generated by Django 3.2.18 on 2023-05-12 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20230512_1336'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredients',
            options={'default_related_name': 'ingridients_in_recipe', 'verbose_name': 'Количество'},
        ),
    ]
