# Generated by Django 3.2.18 on 2023-05-12 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_recipeingredients_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grocerylist',
            options={'default_related_name': 'grocery_list', 'verbose_name_plural': 'Корзина покупок'},
        ),
    ]
