# Generated by Django 3.2.18 on 2023-04-30 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_alter_ingredient_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredients',
            options={'ordering': ['-id']},
        ),
    ]
