# Generated by Django 3.2.18 on 2023-05-12 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_alter_grocerylist_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeingredients',
            options={'default_related_name': 'recipe_ingridients', 'verbose_name': 'Количество'},
        ),
    ]
